config/routes.rb
Rails.application.routes.draw do

  resources :store_images
  resources :stores
  resources :apply_activities
  resources :wx_users
  resources :activity_types
  scope "(:locale)", locale: /en|zh_CN/ do
    resource :wechat, only: [:show, :create]
    resources :users
    resources :activities
    resources :images do
      collection do
          get :idcard
      end
    end

    root "articles#index"
    resources :articles do
      collection do
        get :about
        get :contact
        post :send_message
      end
    end

    #------  admin routes start ----
    namespace :admin, path: "lyp" do
      root "articles#index"
      resources :tags, :categories,:articles
      resources :articles do
        collection do
          post :view
        end
      end
    end
  end
  #------ admin routes end ----
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # make sure this rule is the last one
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :article
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
end

app/models/apply_activity.rb
class ApplyActivity < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_one :access
  validates :title,:category_id,:content, presence: true

  class << self
    def get_conditions params
      search = ['1 = 1 ']
      arr = [[]]
      if params[:search].present?
        search << ' articles.title like ? '
        arr << "%#{params[:search]}%"
      end
      if params[:category].present?
        search << ' articles.category_id = ? '
        arr << params[:category]
      end
      arr[0] = search.join 'and'
      arr.flatten
    end

  end

end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :articles
  validates :name,presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name,:email,:tel,:message

end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_images
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  acts_as_list scope: :store
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_paranoid
  has_many :articles, through: :article_tags,dependent: :destroy
 # has_and_belongs_to_many :articles, join_table: :article_tags
  validates :name,presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :activities
has_many :user_acitivities
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
end

app/models/wechat_session.rb
# Used by wechat gems, do not rename WechatSession to other name,
# Feel free to inherit from other class like ActiveModel::Model
class WechatSession < ActiveRecord::Base
  validates :openid, presence: true, uniqueness: true
  serialize :hash_store, Hash

  # called by wechat gems when user request session
  def self.find_or_initialize_session(request_message)
    find_or_initialize_by(openid: request_message[:from_user_name])
  end

  # called by wechat gems after response Techent server at controller#create
  def save_session(_response_message)
    touch unless new_record? # Always refresh updated_at even no change
    save!
  end
end

app/models/wx_user.rb
class WxUser < ApplicationRecord
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  include ApplicationHelper
  before_action :set_article,only: [:show,:edit,:update,:destroy]

  def index
    @articles = Article.includes(:category,:tags).order("created_at desc")
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
  end

  def create
    @article = Article.new
    respond_to do |format|
      if @article.update article_params
        format.html {redirect_to admin_articles_path,notice: "创建成功！"}
        format.json {render :show, status: :created, location: @article}
      else
        format.html { render :new}
        format.json { render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
  respond_to do |fmt|
    if @article.update article_params
      format.html {redirect_to admin_articles_path, notice: '修改成功！'}
      format.json {render :show, status: :ok, location: @article}
    else
      format.html { render :edit}
      format.json { render json: @article.errors, status: :unprocessable_entity}
    end
  end
  end

  def view
    content = markdown params[:content]
    puts(content)
    render json: {content: content}
  end

  def destroy
    if @article.destroy
      flash[:notice] = '删除成功！'
    else
      flash[:error] = '删除失败！'
    end
    redirect_to admin_articles_path
  end

  private
  def set_article
    begin
    @article = Article.find params[:id]
    rescue => e
      flash[:error] = "找不到数据"
    end
  end

  def article_params
    params.require(:articles).permit(:title, :category_id , :content, tag_ids: [])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < BaseController

  before_action :set_article,only: [:show]

  def index

    @articles = Article.includes(:tags).where(Article.get_conditions params).order('created_at desc').page(params[:page]).per(10)

  end

  def show
    if @article.nil?
      render :file => "/public/404.html", :status => 404,layout: false
    else
      access = Access.find_or_create_by(article_id: @article.id)
      access.update count: (@article.access.count + 1)
    end

  end

  def about

  end

  def contact
    @contact = Contact.new
  end

  #留言
  def send_message
    @contact = Contact.new contact_params
    if @contact.save
      UserMailer.send_msg_to_me(@contact).deliver_now
    end
    redirect_to contact_articles_path,notice: '谢谢您的留言，我会尽快回复您！'
  end

  private
  def set_article
    begin
      @article = Article.find params[:id]
    rescue => e
      flash[:error] = '找不到数据'
    end
  end

  def contact_params
    params.require(:contact).permit(:name, :tel, :email, :message)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wx_users_helper.rb
module WxUsersHelper
end

app/views/admin/articles/_form.html.erb
  <% if article.errors.any? %>
      <div>
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <div class="control-group form-group ">
    <%= f.label :title, "标题：" %>
    <%= f.text_field :title,class: "form-control" %>
  </div>
 <div class="control-group form-group ">
   <%= f.label :category_id, "分类：" %>
   <%= f.select :category_id, Category.all.collect{|c| [c.name ,c.id]},{},class: "form-control" %>
 </div>
  <div class="control-group form-group">
    <label >标签：</label>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, class: "form-control form-group" %>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-1g-6 write-box">
      <%= f.text_area :content , class: "content-body form-control" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-1g-6 preview-box">
      <%= markdown article.content.to_s %>
    </div>
  </div>

<script type="text/javascript">
    $('#article_content').bind('input propertychange', function() {
        preview();
    });

    function preview(){
        $.post(
            "<%= view_admin_articles_path %>",
            {content: $("#article_content").val()},
            function (data) {
                $('.preview-box').html(data['content']);
            },"json"
        );
        /*$.ajax({
            type: "post",
            url: "<#%= view_admin_articles_path %>",
            data: {content: $("#article_content").val()},
            dataType: "json",
            success: function(data){
                $('.preview-box').html(data['content']);
            }
        });*/
    }
</script>

app/views/admin/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/admin/articles/edit.html.erb
<div class="container">
  <h2>修改博客</h2>
  <div class="row">
    <%= form_for :article, {url: admin_article_path(@article),role: "form"} do |f| %>
        <div>
          <%= f.submit "保存" , class: "btn btn-primary save-btn"%>
        </div>
        <%= render partial: 'form', locals: {f: f,article: @article} %>
    <% end %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <h2>博客管理</h2>
      <%= link_to "创建博客", new_admin_article_path,class: "btn btn-primary mb15"  %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <table class="table table-striped table-bordered table-hover my-table">
        <thead>
        <tr>
          <th>标题</th>
          <th>分类</th>
          <th>标签</th>
          <th >操作</th>
        </tr>
        </thead>

        <tbody>
        <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <td><%= article.category.try(:name) %></td>
              <td>
                <% article.tags.each do |tag| %>
                <span class="tag"><%= tag.name %></span>
                <% end %>
              </td>
              <td><%= link_to '预览', edit_admin_article_path(article),class: "btn btn-primary" %>
              <%= link_to '修改', edit_admin_article_path(article),class: "btn btn-primary" %>
              <%= link_to '删除', admin_article_path(article), method: :delete, data: { confirm: '确定要删除?' } ,class: "btn btn-danger"%></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
<div class="container">
  <h2>新增博客</h2>
  <div class="row">
    <%= form_for :article, {url: admin_articles_path,role: "form"} do |f| %>
    <div>
      <%= f.submit "保存" , class: "btn btn-primary save-btn"%>
    </div>
     <%= render partial: 'form', locals: {f: f,article: @article} %>
    <% end %>
  </div>
</div>

app/views/admin/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/articles/_content.html.erb
<% @articles.each do |article| %>
  <h2>
    <%= link_to article.title ,article_path(article) %>
    <small>
      <% article.tags.each do |tag| %>
        <span class="tag"><%= tag.name %></span>
      <% end %>
    </small>
  </h2>
    <div>
      <%= article.content.to_s.truncate(200) %>
    </div>
    <br>
    <p class="grey">
      <%= image_tag 'me.jpg', alt: 'lyp', class: 'author-thumb' %><i class="fa fa-clock-o"></i>   <%= article.created_at.strftime('%F') %>
    </p>
<% end %>

<div class="page-box">
  <%= link_to_prev_page @articles,"上一页", remote: true,params: params.permit(:search, :category),class: 'prev-page' %>
  <%= link_to_next_page @articles,"下一页", remote: true,params: params.permit(:search, :category),class: 'next-page' %>
</div>

app/views/articles/about.html.erb
<div class="col-md-8">
  <div class="col-md-6">
    <%= image_tag 'me.jpg',style: "width:60%;border-radius:100%;" %>
  </div>
  <div class="col-md-6">

    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">关于我</h3>
      </div>
      <div class="panel-body">
        <p>姓名：李有平</p>
        <p>生日：04-04</p>
        <p>邮箱：453974610@qq.com</p>
        <p>籍贯：江西省上饶市</p>
        <p>现居：上海</p>
      </div>
    </div>
  </div>
</div>

app/views/articles/contact.html.erb
<div class="col-md-8 control-group form-group ">

  <h3>给我留言：</h3>
  <%= form_for @contact, url: send_message_articles_path, id: 'contactForm' do |f| %>
      <div class="control-group form-group">

      <%= f.label :name,"姓名：" %>
      <%= f.text_field :name ,class: "form-control" %>
      </div>
      <div class="control-group form-group">
      <%= f.label :name,"手机：" %>
      <%= f.text_field :tel ,class: "form-control", maxlength: 11 %>
      </div>
      <div class="control-group form-group">
      <%= f.label :name,"邮箱：" %>
      <%= f.text_field :email ,class: "form-control" ,maxlength:20 %>
      </div>
      <div class="control-group form-group">
      <%= f.label :message,"内容：" %>
      <%= f.text_area :message,class: "form-control" ,maxlength:800,style:"resize:none" , id:"message",rows:10,cols: 100  %>
      </div>
      <%= f.submit '发送',class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="col-md-8" id="articles">
<%= render partial: "articles/content" %>
</div>

app/views/articles/show.html.erb
<div class="col-md-8">
  <h1><%= @article.title %></h1>
  <hr>
  <div class="markdown">
    <%=  markdown @article.content %>
  </div>
  <br>
  <p><%= image_tag 'me.jpg', alt: 'lyp', class: 'author-thumb' %><i class="fa fa-clock-o"></i> <%= @article.created_at.strftime('%F') %></p>
</div>