config/routes.rb
Rails.application.routes.draw do

  resources :store_images
  resources :stores
  resources :apply_activities
  resources :wx_users
  resources :activity_types
  scope "(:locale)", locale: /en|zh_CN/ do
    resource :wechat, only: [:show, :create]
    resources :users
    resources :activities
    resources :images do
      collection do
          get :idcard
      end
    end

    root "articles#index"
    resources :articles do
      collection do
        get :about
        get :contact
        post :send_message
      end
    end

    #------  admin routes start ----
    namespace :admin, path: "lyp" do
      root "articles#index"
      resources :tags, :categories,:articles
      resources :articles do
        collection do
          post :view
        end
      end
    end
  end
  #------ admin routes end ----
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # make sure this rule is the last one
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :article
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
end

app/models/apply_activity.rb
class ApplyActivity < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_one :access
  validates :title,:category_id,:content, presence: true

  class << self
    def get_conditions params
      search = ['1 = 1 ']
      arr = [[]]
      if params[:search].present?
        search << ' articles.title like ? '
        arr << "%#{params[:search]}%"
      end
      if params[:category].present?
        search << ' articles.category_id = ? '
        arr << params[:category]
      end
      arr[0] = search.join 'and'
      arr.flatten
    end

  end

end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :articles
  validates :name,presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name,:email,:tel,:message

end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_images
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  acts_as_list scope: :store
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_paranoid
  has_many :articles, through: :article_tags,dependent: :destroy
 # has_and_belongs_to_many :articles, join_table: :article_tags
  validates :name,presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :activities
has_many :user_acitivities
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
end

app/models/wechat_session.rb
# Used by wechat gems, do not rename WechatSession to other name,
# Feel free to inherit from other class like ActiveModel::Model
class WechatSession < ActiveRecord::Base
  validates :openid, presence: true, uniqueness: true
  serialize :hash_store, Hash

  # called by wechat gems when user request session
  def self.find_or_initialize_session(request_message)
    find_or_initialize_by(openid: request_message[:from_user_name])
  end

  # called by wechat gems after response Techent server at controller#create
  def save_session(_response_message)
    touch unless new_record? # Always refresh updated_at even no change
    save!
  end
end

app/models/wx_user.rb
class WxUser < ApplicationRecord
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:title, :sub_title, :icon, :tel_num, :landline, :show_landline, :address, :detail)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wx_users_helper.rb
module WxUsersHelper
end

app/views/stores/_form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sub_title %>
    <%= f.text_field :sub_title %>
  </div>

  <div class="field">
    <%= f.label :icon %>
    <%= f.text_field :icon %>
  </div>

  <div class="field">
    <%= f.label :tel_num %>
    <%= f.text_field :tel_num %>
  </div>

  <div class="field">
    <%= f.label :landline %>
    <%= f.text_field :landline %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub title</th>
      <th>Icon</th>
      <th>Tel num</th>
      <th>Landline</th>
      <th>Address</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.title %></td>
        <td><%= store.sub_title %></td>
        <td><%= store.icon %></td>
        <td><%= store.tel_num %></td>
        <td><%= store.landline %></td>
        <td><%= store.address %></td>
        <td><%= store.detail %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @store.title %>
</p>

<p>
  <strong>Sub title:</strong>
  <%= @store.sub_title %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @store.icon %>
</p>

<p>
  <strong>Tel num:</strong>
  <%= @store.tel_num %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @store.landline %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @store.detail %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>