config/routes.rb
Rails.application.routes.draw do

  resources :store_images
  resources :stores
  resources :apply_activities
  resources :wx_users
  resources :activity_types
  scope "(:locale)", locale: /en|zh_CN/ do
    resource :wechat, only: [:show, :create]
    resources :users
    resources :activities
    resources :images do
      collection do
          get :idcard
      end
    end

    root "articles#index"
    resources :articles do
      collection do
        get :about
        get :contact
        post :send_message
      end
    end

    #------  admin routes start ----
    namespace :admin, path: "lyp" do
      root "articles#index"
      resources :tags, :categories,:articles
      resources :articles do
        collection do
          post :view
        end
      end
    end
  end
  #------ admin routes end ----
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # make sure this rule is the last one
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :article
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
end

app/models/apply_activity.rb
class ApplyActivity < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_one :access
  validates :title,:category_id,:content, presence: true

  class << self
    def get_conditions params
      search = ['1 = 1 ']
      arr = [[]]
      if params[:search].present?
        search << ' articles.title like ? '
        arr << "%#{params[:search]}%"
      end
      if params[:category].present?
        search << ' articles.category_id = ? '
        arr << params[:category]
      end
      arr[0] = search.join 'and'
      arr.flatten
    end

  end

end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :articles
  validates :name,presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name,:email,:tel,:message

end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_images
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  acts_as_list scope: :store
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_paranoid
  has_many :articles, through: :article_tags,dependent: :destroy
 # has_and_belongs_to_many :articles, join_table: :article_tags
  validates :name,presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :activities
has_many :user_acitivities
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
end

app/models/wechat_session.rb
# Used by wechat gems, do not rename WechatSession to other name,
# Feel free to inherit from other class like ActiveModel::Model
class WechatSession < ActiveRecord::Base
  validates :openid, presence: true, uniqueness: true
  serialize :hash_store, Hash

  # called by wechat gems when user request session
  def self.find_or_initialize_session(request_message)
    find_or_initialize_by(openid: request_message[:from_user_name])
  end

  # called by wechat gems after response Techent server at controller#create
  def save_session(_response_message)
    touch unless new_record? # Always refresh updated_at even no change
    save!
  end
end

app/models/wx_user.rb
class WxUser < ApplicationRecord
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all.order('created_at desc')
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tags_path, notice: '标签创建成功！' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_tags_path, notice: '标签修改成功！' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    if @tag.article_tags.present?
      flash[:error] = '删除失败，有博客下有此标签！'
    else
      respond_to do |format|
        if  @tag.destroy
        format.html { redirect_to admin_tags_url, notice: '标签删除成功！' }
        format.json { head :no_content }
        else
          format.html { redirect_to admin_tags_url, notice: '标签删除失败！' }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      begin
        @tag= Tag.find params[:id]
      rescue => e
        flash[:error] = '找不到数据'
        redirect_to admins_tags_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wx_users_helper.rb
module WxUsersHelper
end

app/views/admin/tags/_form.html.erb
<div class="row">

      <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
        <%= f.submit "保存" , class: "btn btn-primary save-btn"%> <%= link_to "返回",admin_tags_path,class: "btn btn-primary back-btn" %>
      </div>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="col-xs-12 col-sm-12 col-md-4 col-1g-4 control-group form-group ">
    <%= f.label :name, "标签名" %>
    <%= f.text_field :name,class: "form-control" %>
  </div>

</div>

app/views/admin/tags/edit.html.erb
<div class="container">
  <h2>修改标签</h2>
  <%= form_for(@tag, {url: admin_tag_path(@tag),role: "form"}) do |f| %>
  <%= render partial: 'form',locals:{tag: @tag ,f: f} %>
  <% end %>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <h2>标签管理</h2>
      <%= link_to '创建标签', new_admin_tag_path,class: "btn btn-primary mb15" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <table class="table table-striped table-bordered table-hover my-table">
        <thead>
          <tr>
            <th>标签名</th>
            <th colspan="2">操作</th>
          </tr>
        </thead>

        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= link_to '修改', edit_admin_tag_path(tag),class: "btn btn-primary" %></td>
              <td><%= link_to '删除', admin_tag_path(tag), method: :delete, data: { confirm: '确定要删除?' },class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/tags/new.html.erb
<div class="container">
  <h2>新增标签</h2>
  <%= form_for(@tag, {url: admin_tags_path,role: "form"}) do |f| %>
      <%= render partial: 'form',locals:{tag: @tag ,f: f} %>
  <% end %>
</div>

app/views/admin/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @tag.deleted_at %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>