config/routes.rb
Rails.application.routes.draw do

  resources :store_images
  resources :stores
  resources :apply_activities
  resources :wx_users
  resources :activity_types
  scope "(:locale)", locale: /en|zh_CN/ do
    resource :wechat, only: [:show, :create]
    resources :users
    resources :activities
    resources :images do
      collection do
          get :idcard
      end
    end

    root "articles#index"
    resources :articles do
      collection do
        get :about
        get :contact
        post :send_message
      end
    end

    #------  admin routes start ----
    namespace :admin, path: "lyp" do
      root "articles#index"
      resources :tags, :categories,:articles
      resources :articles do
        collection do
          post :view
        end
      end
    end
  end
  #------ admin routes end ----
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # make sure this rule is the last one
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :article
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
end

app/models/apply_activity.rb
class ApplyActivity < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_one :access
  validates :title,:category_id,:content, presence: true

  class << self
    def get_conditions params
      search = ['1 = 1 ']
      arr = [[]]
      if params[:search].present?
        search << ' articles.title like ? '
        arr << "%#{params[:search]}%"
      end
      if params[:category].present?
        search << ' articles.category_id = ? '
        arr << params[:category]
      end
      arr[0] = search.join 'and'
      arr.flatten
    end

  end

end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :articles
  validates :name,presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name,:email,:tel,:message

end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_images
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  acts_as_list scope: :store
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_paranoid
  has_many :articles, through: :article_tags,dependent: :destroy
 # has_and_belongs_to_many :articles, join_table: :article_tags
  validates :name,presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :activities
has_many :user_acitivities
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
end

app/models/wechat_session.rb
# Used by wechat gems, do not rename WechatSession to other name,
# Feel free to inherit from other class like ActiveModel::Model
class WechatSession < ActiveRecord::Base
  validates :openid, presence: true, uniqueness: true
  serialize :hash_store, Hash

  # called by wechat gems when user request session
  def self.find_or_initialize_session(request_message)
    find_or_initialize_by(openid: request_message[:from_user_name])
  end

  # called by wechat gems after response Techent server at controller#create
  def save_session(_response_message)
    touch unless new_record? # Always refresh updated_at even no change
    save!
  end
end

app/models/wx_user.rb
class WxUser < ApplicationRecord
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order('created_at desc')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: '分类创建成功' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)

        format.html { redirect_to admin_categories_path, notice: '分类修改成功！' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @category.articles.present?
      flash[:error] = '删除失败,该分类下还有博客！'
    else
      respond_to do |format|
        if  @category.destroy
        format.html { redirect_to admin_categories_url, notice: '分类删除成功！' }
        format.json { head :no_content }
        else
          format.html { redirect_to admin_categories_url, error: '分类删除失败！' }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue => e
        flash[:error] = '找不到数据'
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wx_users_helper.rb
module WxUsersHelper
end

app/views/admin/categories/_form.html.erb
<div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
          <%= f.submit "保存" , class: "btn btn-primary save-btn"%> <%= link_to "返回",admin_categories_path,class: "btn btn-primary back-btn" %>
        </div>
      <% if category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <div class="col-xs-12 col-sm-12 col-md-4 col-1g-4 control-group form-group ">
        <%= f.label :name,"分类名" %>
        <%= f.text_field :name ,class: "form-control"%>
      </div>

</div>

app/views/admin/categories/edit.html.erb
<div class="container">
<h2>修改分类</h2>
  <%= form_for(@category, {url: admin_category_path(@category),role: "form"}) do |f| %>
    <%= render partial: 'form', locals: {f: f,category: @category} %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <h2>分类管理</h2>
      <%= link_to '创建分类', new_admin_category_path,class: "btn btn-primary mb15" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-1g-12">
      <table class="table table-striped table-bordered table-hover my-table">
        <thead>
          <tr>
            <th>分类名</th>
            <th colspan="2">操作</th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= link_to '修改', edit_admin_category_path(category),class: "btn btn-primary" %></td>
              <td><%= link_to '删除', admin_category_path(category), method: :delete, data: { confirm: '确定要删除?' } ,class: "btn btn-danger"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
<h2>新增分类</h2>
  <%= form_for(@category, {url: admin_categories_path,role: "form"}) do |f| %>
      <%= render partial: 'form', locals: {f: f, category: @category} %>
  <% end %>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @category.deleted_at %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>